apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    app: webserver
