apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init
  namespace: clalit
spec:
  template:
    spec:
      containers:
      - name: mysql-init
        image: mysql:latest
        command:
        - mysql
        - -h
        - mysql
        - -u
        - root
        - -p
        - password
        - -e
        - "CREATE DATABASE IF NOT EXISTS mydb; USE mydb; CREATE TABLE IF NOT EXISTS users(id INT PRIMARY KEY, name VARCHAR(100));"
      restartPolicy: OnFailure