apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: vladimirkogan/clalit:1.0.2
        args:
        - --port=${SERVER_PORT}
        - --db_host_name=mysql
        - --username=root
        - --password=${MYSQL_ROOT_PASSWORD}
        volumeMounts:
        - name: templates-volume
          mountPath: /templates
      volumes:
      - name: templates-volume
        hostPath:
          path: $(pwd)/templates