apiVersion: v1
kind: Service
metadata:
  name: clalit-web-server
  namespace: clalit
spec:
  selector:
    app: clalit-web-server
  ports:
    - name: clalit-web-server-listener
      protocol: TCP
      port: {{ .Values.server.port}}
      targetPort: {{ .Values.server.port}}
  type: LoadBalancer