apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: clalit
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: {{ .Values.container.image}}
        env:
        - name: db_host_name
          value: mysql
        - name: db_user_name
          value: root
        - name: db_password
          value: password
        volumeMounts:
        - name: templates-volume
          mountPath: /templates
      volumes:
      - name: templates-volume
        hostPath:
          path: /templates