apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.projectName}}-db-credentials
type: Opaque
data:
  password: cGFzc3dvcmQ=  # base64 for password
  user: cm9vdA==  # base64 for 'root'
  name: dW1z  # base64 for 'ums'
  host: bXlzcWw=  # base64 for 'mysql'