apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.projectName}}-db-pvc
  namespace: clalit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi