apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.global.projectName}}-route
spec:
  to:
    kind: Service
    name: {{ .Values.global.projectName}}-service
  port:
    targetPort: 8080