apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - {{ .Values.database.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.database.pvc.storage }}
