apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: "{{ .Values.web.image }}:{{ .Values.web.tag }}"
          ports:
            - containerPort: {{ .Values.web.port }}
          volumeMounts:
            - name: postgres-pvc
              mountPath: /usr/share/nginx/html
      volumes:
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc