apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - {{ .Values.database.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.database.pvc.storage }}
