apiVersion: v1
kind: Service
metadata:
  name: web-server
  namespace: {{ .Values.global.namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
      nodePort: 30080
  selector:
    app: web-server
